services:
  api:
    # image: andi107/node-starter-api
    image: node-starter-src
    ports:
      - "3002:80"
    env_file:
      - ./root/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
