services:
  api:
    image: andi107/node-starter-api
    ports:
      - "3000:80"
    env_file:
      - ./src/.env
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
